=== thehendl/ssd/ex1.dtd
<!ELEMENT cinemas (postaldata, cinema+)> <!--postaldata, one or more cinema-->
        <!ELEMENT postaldata (postal+)> <!--one or more postal-->

        <!ELEMENT postal (#PCDATA)> <!--text-->
        <!ATTLIST postal id ID #REQUIRED> <!--PLZ id requiered-->

        <!ELEMENT cinema (location, postalID, cinemaname+, movies*)> <!--one or more cinemanames, zero or more movies-->
        <!ATTLIST cinema location #REQUIRED> <!--location required-->
        <!ATTLIST cinema postalID IDREF #REQUIRED> <!--IDref postalID required-->

        <!ELEMENT cinemaname (#PCDATA)>  <!--text in cinemaname-->

        <!ELEMENT movies (title? )> <!--zero or one title-->


        <!ELEMENT title (#PCDATA, year?, origin?)> <!--text, zero or one year and origin-->
        <!ATTLIST title id ID
                ref IDREF #IMPLIED> <!--title id  #ID and #IDREF #IMPLIED-->

        <!ELEMENT year (#PCDATA)> <!--text in year-->

        <!ELEMENT origin (#PCDATA)> <!--text in origin-->

=== thehendl/ssd/ex1-2-nv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ex1dtd SYSTEM "ex1.dtd">

<cinemas>
    <!-- Postal data with unique IDs -->
    <postaldatas> <!-- postaldatas isnt an existing element-->
        <postal ip="post3"> <!-- id is required-->
            1030
        </postal>
        <postal id="post9">
            1090
        </postal>
    </postaldatas>

    <cinema  postalID="post3">
        <cinemaname>art house cinema</cinemaname>
        <cinemaname>landstra√üe kinoplex</cinemaname>
        <movies>
            <title id="tit7">
                a space odyssey
                <year>1968</year>
                <origin country= "US"> </origin> <!-- attribute instead of pcdata in origin-->
            </title>
            <title id="tit8">
                la dolce vita
                <origin>IT</origin>
            </title>
        </movies>
    </cinema>

    <cinema location="alsergrund" postalID="post9">
        <cinemaname>retro theater</cinemaname>
        <movies>
            <title id="tit9">
                bicycle thieves
                <year>1948</year>
                <origin>IT</origin>
            </title>
            <title ref="tit7">
            </title>
        </movies>
    </cinema>

    <cinema location="neubau" postalID="post9">
        <cinemaname>indie film club</cinemaname>
    </cinema>
</cinemas>

=== thehendl/ssd/ex1-3-nv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ex1dtd SYSTEM "ex1.dtd">

<cinemas>
    <postaldata>
        <postal id="post7">1070</postal>
        <postal id="post10">1100</postal>
    </postaldata>

    <cinema location="neubau" postalID="post7">
        <cinemaname>neubau cinema center</cinemaname>
        <movies>
            <title id="tit10">
                the grand budapest hotel
                <year>2014</year>
                <origin>US</origin>
            </title>
        </movies>
    </cinema>

    <cinema location="favoriten" postalID="post10">
        <cinemaname>favoriten multiplex</cinemaname>
        <movies>
            <title id="tit11">
                spirited away
                <year>2001</year>
                <year>2002</year> <!-- more than one year................. -->
                <origin>JAP</origin>
            </title>

        </movies>
    </cinema>


</cinemas>

=== thehendl/ssd/ex1/ex1-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ex1dtd SYSTEM "ex1.dtd">

<cinemas>
    <!-- Postal data with unique IDs -->
    <postaldata>
        <postal id="post3">
            1030
        </postal>
        <postal id="post9">
            1090
        </postal>
    </postaldata>

    <cinema location="landstraße" postalID="post3">
        <cinemaname>art house cinema</cinemaname>
        <cinemaname>landstraße kinoplex</cinemaname>
        <movies>
            <title id="tit7">
                a space odyssey
                <year>1968</year>
                <origin>US</origin>
            </title>
            <title id="tit8">
                la dolce vita
                <origin>IT</origin>
            </title>
        </movies>
    </cinema>

    <cinema location="alsergrund" postalID="post9">
        <cinemaname>retro theater</cinemaname>
        <movies>
            <title id="tit9">
                bicycle thieves
                <year>1948</year>
                <origin>IT</origin>
            </title>
            <title ref="tit7">
            </title>
        </movies>
    </cinema>

    <cinema location="neubau" postalID="post9">
        <cinemaname>indie film club</cinemaname>
    </cinema>
</cinemas>

=== thehendl/ssd/ex1-0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ex1dtd SYSTEM "ex1.dtd">


<cinemas>
    <postaldata>
        <postal id="post1">
            1010
        </postal>
        <postal id="post5">
            1050
        </postal>
    </postaldata>
    <cinema location="innere stadt" postalID="post1"> <!--element content with attribute-->
        <cinemaname> <!--simple content-->
            burgkino
        </cinemaname>
        <movies>
            <title id="tit1">
                the third man
                <year>
                    1949
                </year>
                <origin>
                    GB
                </origin>
            </title>
            <title id="tit2">
                favoriten
                <year>
                    2024
                </year> <!--mixed content-->
                <origin>
                    AT
                </origin>
            </title>

        </movies>
    </cinema>

    <cinema location="margarethen" postalID="1050">
        <cinemaname>
            filmmcasino
        </cinemaname>
        <movies>
            <title id="tit3">
                der junge &amp; der reiher <!--character reference-->
                <year>
                    2024
                </year>
                <origin>
                    JAP
                </origin>
            </title>
        </movies>
    </cinema>

</cinemas>

=== thehendl/ssd/ex1/ex1-1-nv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ex1dtd SYSTEM "ex1.dtd">

<cinemas>
    <!-- Postal data with different postal IDs -->
    <postaldata>
        <postal id="post2">
            1020
        </postal>
        <postal id="post20">
            1200
        </postal>
    </postaldata>

    <cinemas location="leopoldstadt" postalID="post2"> <!--no validation because missspelling cinema and breaking cinemas rules-->
        <cinemaname>kino leopold</cinemaname>
        <movies>
            <title id="tit4">
                sunset boulevard
                <year>1950</year>
                <origin>US</origin>
            </title>
            <title id="tit5">
                metropolis
                <year>1927</year>
                <origin>DE</origin>
            </title>
        </movies>
    </cinemas>

    <cinema location="brigittenau" postalID="post20">
        <cinemaname>brigittenauer kino</cinemaname>
        <movies>
            <title id="tit6">
                the cabinet of dr. caligari
                <year>1920</year>
                <origin>DE</origin>
            </title>
            <title ref="tit4">
                <!-- References the movie with id="tit4" -->
            </title>
        </movies>
    </cinema>

</cinemas>
