=== thehendl/ssd/ex6/takeout.dtd
<!ELEMENT takeout (offered-dishes,personnel,current-orders)>

        <!ELEMENT offered-dishes (dish+)>
        <!ELEMENT dish (#PCDATA)>
        <!ATTLIST dish id ID #REQUIRED>
        <!ATTLIST dish name CDATA #REQUIRED>
        <!ATTLIST dish vegetarian (true|false) #REQUIRED>

        <!ELEMENT personnel (person+)>
        <!ELEMENT person (name,transport?)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT transport (#PCDATA)>
        <!ATTLIST person id ID #REQUIRED>

        <!ELEMENT current-orders (order*)>
        <!ELEMENT order ((address|self-pickup),item+)>
        <!ATTLIST order order-id ID #REQUIRED>

        <!ELEMENT address (#PCDATA)>
        <!ATTLIST address deliveredBy IDREF #REQUIRED>
        <!ELEMENT self-pickup EMPTY>
        <!ATTLIST self-pickup client-name CDATA #REQUIRED>

        <!ELEMENT item EMPTY>
        <!ATTLIST item dish IDREF #REQUIRED>
        <!ATTLIST item price CDATA #REQUIRED>

=== thehendl/ssd/takeout.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE takeout SYSTEM "takeout.dtd">
<takeout>
    <!-- dishes -->
    <offered-dishes>
        <dish id="D1" name="pizza margherita" vegetarian="true"/>
        <dish id="D2" name="pizza pepperoni" vegetarian="false"/>
        <dish id="D3" name="veggieburger" vegetarian="true"/>
        <dish id="D4" name="cheeseburger" vegetarian="false"/>
        <dish id="D5" name="pasta" vegetarian="true"/>
        <dish id="D6" name="steak" vegetarian="false"/>
        <dish id="D7" name="salad" vegetarian="true"/>
        <dish id="D8" name="fish" vegetarian="false"/>
    </offered-dishes>

    <!-- personnel -->
    <personnel>
        <person id="P1">
            <name>franz gross</name>
            <transport>car</transport>
        </person>
        <person id="P2">
            <name>julia klein</name>
            <transport>bike</transport>
        </person>
        <person id="P3">
            <name>lisa ertl</name>
            <transport>motorbike</transport>
        </person>
        <person id="P4">
            <name>heidi bauer</name>
        </person>
    </personnel>

    <!-- current orders -->
    <current-orders>
        <!-- order 1 -->
        <order order-id="O1" total-price="22.48">
            <address deliveredBy="P1">paniglgasse 15, 1040</address>
            <item dish="D1" price="12.99"/>
            <item dish="D3" price="9.49"/>
        </order>
        <!-- order 2 -->
        <order order-id="O2" total-price="24.48">
            <self-pickup client-name="alex mueller"/>
            <item dish="D2" price="15.49"/>
            <item dish="D4" price="8.99"/>
        </order>
        <!-- order 3 -->
        <order order-id="O3" total-price="45.97">
            <address deliveredBy="P2">franzgasse 12, 1020</address>
            <item dish="D5" price="13.99"/>
            <item dish="D6" price="22.49"/>
            <item dish="D3" price="9.49"/>
        </order>
        <!-- order 4 -->
        <order order-id="O4" total-price="20.98">
            <self-pickup client-name="michael berger"/>
            <item dish="D7" price="7.99"/>
            <item dish="D1" price="12.99"/>
            <item dish="D6" price="22.49"/>
        </order>

    </current-orders>
</takeout>
